language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - android-24

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

before_script:
    - android update sdk --no-ui --all --filter build-tools-25.0.0,android-24,extra-android-m2repository

script:
    - ./gradlew test
